[Eth]
# Set your custom network ID to match your genesis.json chainId
NetworkId = 2319
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
# Customize gas limits and price for your private network
GasCeil = 140000000
GasPrice = 1000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
# Customize the IPC and HTTP configuration
IPCPath = "geth.ipc"
HTTPHost = "localhost"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"] # Add "admin" if needed for node management
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
# Disable connection to public BSC nodes
MaxPeers = 50
NoDiscovery = true # Disable peer discovery for private blockchain
StaticNodes = []   # Define specific nodes for your private network (add later if needed)
ListenAddr = ":30303"
EnableMsgEvents = false

[Node.LogConfig]
# Customize logging for better debugging
FilePath = "private-bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
